### ISSUE TITLE
Cannot read property 'ZoneGroup'

### ISSUE THREAD

**Issue by C3dr1c** [clemenstyp/sonos-web-docker#1]
I've deployed the docker container on my Synology Diskstation (running the latest rev.6.2.2-24922). Everything seems to go well through the installation, but the following error occurs when starting. It does start the web page by searching for the sonos installation, so the engine starts. 
However, after 10 seconds the error displays:

An unexpected error occurred while searching for your Sonos System: {"stack":"TypeError: Cannot read property 'ZoneGroup' of undefined\n at GetZoneGroupState.then (/root/.sonos-web/node_modules/sonos/lib/services/ZoneGroupTopology.js:46:76)\n at <anonymous>\n at process._tickCallback (internal/process/next_tick.js:189:7)","message":"Cannot read property 'ZoneGroup' of undefined"}

According to the sonos-web github page (https://github.com/Villarrealized/sonos-web/issues/11), this issue has been fixed in v0.9.4
What to do, to get the container updated?

Kind regards,

Cedric

**Comment by MLDMoritz** [comment]
Getting the same problem with initial installation (Version is 1.2.0 however!)

This is what I did to get it working:
Open a bash shell to the container. Execute `sonos-web update`
