### ISSUE TITLE
Cannot read property 'forEach' 

### ISSUE THREAD

**Issue by JamesDAdams** [clemenstyp/sonos-web-docker#2]
Hi,

i have this error on the web page : 

`An unexpected error occurred while searching for your Sonos System: {"stack":"TypeError: Cannot read property 'forEach' of undefined\n at SonosNetwork._getQueue (/root/.sonos-web/src/sonos/SonosNetwork.js:715:19)\n at <anonymous>\n at process._tickCallback (internal/process/next_tick.js:189:7)","message":"Cannot read property 'forEach' of undefined"}`

**Comment by JamesDAdams** [comment]
I edit this file https://github.com/Villarrealized/sonos-web/pull/65/files

in /root/.sonos-web/src/sonos/SonosNetwork.js
